---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: "instala httpd"
    package:
      name: httpd
      state: latest
  - name: "iniciar el servicio"
    service:
      name: httpd
      state: started
      enabled: yes
  - name: "crea index.html"
    file:
      path: /var/www/html/index.html
      state: touch
  - name: "mete contenido"
    copy:
      dest: /var/www/html/index.html
      content: "hola mundo cruel !"


